import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const config = [
  ...nextVitals,
  ...nextTs,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "tests/e2e/**",
      "next-env.d.ts",
      // Generated by scripts/build-icons.mjs
      "lib/icon-data.ts",
      // Tooling that ships with the Claude skills, not app code
      ".claude/**",
    ],
  },
  {
    // The React Compiler rules flag patterns the app already uses on purpose
    // (resetting state when an input changes, reading the clock while
    // filtering). They stay visible as warnings to clean up over time.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/purity": "warn",
    },
  },
]

export default config
