// Dashboard: import behind an icon (opens, Escape/outside closes), department tabs pinned to the bottom while scrolling.
const { LAUNCH, APP_URL } = require('./env');
const { chromium } = require('playwright'); const { signedIn } = require('./auth-mock');
let fails = 0; const pass = (ok, l) => { fails += !ok; console.log(`   ${ok ? 'PASS' : 'FAIL'} ${l}`); };
const now = new Date().toISOString();
const data = Array.from({ length: 14 }, (_, k) => ({ id: k, equipment: `Med ${k}`, sector: 'health', business_type: 'pharmacie', severity: k % 2 ? 'WARNING' : 'CRITICAL', date: now, alert_key: 'health.stock.low', message: `MSG ${k}` }));
(async () => { const b = await chromium.launch(LAUNCH);
  const p = await b.newPage({ viewport: { width: 1440, height: 900 }, locale: 'en-US' }); const errs = []; p.on('pageerror', e => errs.push(e.message));
  await p.route(/onrender\.com\//, r => r.fulfill({ status: 200, contentType: 'application/json', body: /\/alerts/.test(r.request().url()) ? JSON.stringify(data) : '{"recommendations":[],"assignments":[],"contractors":[]}' }));
  await p.addInitScript(() => { if (!sessionStorage.x) { sessionStorage.x = 1; localStorage.clear(); Object.entries({ sentria_language: 'en', sentria_onboarded: 'true', sentria_sector: 'health', sentria_sectors: '["health"]', sentria_business_type: 'pharmacie', sentria_departments: '{"health":["pharmacie","clinique-hopital"]}' }).forEach(([k, v]) => localStorage.setItem(k, v)); } });
  await signedIn(p, 'u', 'a@b.c', { plan: 'business' }); await p.goto(APP_URL); await p.waitForTimeout(1800);
  const icon = p.locator('button[aria-controls=import-panel]');
  pass(await p.locator('#import-panel').isHidden() && !/Choose a sector, then import/.test(await p.evaluate(() => document.querySelector('main').innerText)), 'no Import card on the page: just an icon');
  pass(await icon.getAttribute('aria-label') === 'Import data', 'icon has a name: "Import data"');
  await icon.click(); await p.waitForTimeout(150);
  pass(await p.locator('#import-panel').isVisible() && await icon.getAttribute('aria-expanded') === 'true', 'click: import panel opens');
  await p.screenshot({ path: 'D-import-open.png' });
  await p.keyboard.press('Escape'); await p.waitForTimeout(300); // the panel plays a 150 ms exit (transitions.dev dropdown) before it is hidden
  pass(await p.locator('#import-panel').isHidden(), 'Escape closes it');
  await icon.click(); await p.mouse.click(700, 600); await p.waitForTimeout(300);
  pass(await p.locator('#import-panel').isHidden(), 'click outside closes it');
  const tabs = p.getByRole('tablist', { name: 'Your departments' });
  const bottom0 = await tabs.evaluate(e => Math.round(e.getBoundingClientRect().bottom));
  await p.evaluate(() => document.querySelector('main').scrollTo(0, 900)); await p.waitForTimeout(200);
  const bottom1 = await tabs.evaluate(e => Math.round(e.getBoundingClientRect().bottom));
  const mainBottom = await p.evaluate(() => Math.round(document.querySelector('main').getBoundingClientRect().bottom));
  pass(bottom1 <= mainBottom && bottom1 >= mainBottom - 30 && bottom0 >= mainBottom - 30 && await p.evaluate(() => document.querySelector('main').scrollTop) > 500, `tabs stay pinned at the bottom while scrolling (${bottom0} → ${bottom1}, main ${mainBottom})`);
  await icon.click(); await p.waitForTimeout(150);
  pass(await p.locator('#import-panel').isVisible(), 'icon still reachable after scrolling');
  await p.keyboard.press('Escape');
  await p.screenshot({ path: 'D-scrolled.png' });
  await tabs.getByRole('tab', { name: /Clinic/ }).click(); await p.waitForTimeout(400);
  pass(await tabs.getByRole('tab', { name: /Clinic/ }).getAttribute('aria-selected') === 'true', 'tab switch works');
  pass(await p.evaluate(() => !!document.querySelector('header #topbar-actions button[aria-controls=import-panel]')), 'upload icon sits in the top bar');
  await p.goto(APP_URL); await p.waitForTimeout(1500);
  pass(errs.length === 0, 'no page errors ' + errs.join('|'));
  await b.close(); console.log(`\n${fails ? fails + ' failure(s)' : 'ALL OK'}`); process.exit(fails ? 1 : 0); })();
