// Generated by scripts/build-icons.mjs. Do not edit by hand.
"use client"

import { forwardRef, type CSSProperties, type ForwardRefExoticComponent, type RefAttributes, type SVGProps } from "react"

import { ICON_DATA } from "./icon-data"

export type IconProps = Omit<SVGProps<SVGSVGElement>, "ref"> & {
  /** Lucide's stroke width (2 = normal). Scaled to the icon set's 1.5. */
  strokeWidth?: number | string
  size?: number | string
}

export type LucideIcon = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>

function make(name: string): LucideIcon {
  const data = ICON_DATA[name]
  const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
    { strokeWidth, size = 24, style, className, ...rest },
    ref
  ) {
    const custom = strokeWidth !== undefined && Number(strokeWidth) !== 2
    const iconStyle: CSSProperties | undefined = custom
      ? { ...style, ["--icon-sw" as string]: String(Number(strokeWidth) * 0.75) }
      : style
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox={data.viewBox}
        fill="none"
        aria-hidden={rest["aria-label"] ? undefined : true}
        focusable="false"
        className={custom ? (className ? className + " icon-sw" : "icon-sw") : className}
        style={iconStyle}
        {...rest}
        dangerouslySetInnerHTML={{ __html: data.body }}
      />
    )
  })
  Icon.displayName = name
  return Icon
}

export const Activity = make("Activity")
export const AlertTriangle = make("AlertTriangle")
export const Anchor = make("Anchor")
export const AtSign = make("AtSign")
export const ArrowLeft = make("ArrowLeft")
export const ArrowLeftRight = make("ArrowLeftRight")
export const ArrowRight = make("ArrowRight")
export const ArrowUp = make("ArrowUp")
export const ArrowUpRight = make("ArrowUpRight")
export const BatteryCharging = make("BatteryCharging")
export const Bell = make("Bell")
export const BellRing = make("BellRing")
export const Bot = make("Bot")
export const Boxes = make("Boxes")
export const BrainCircuit = make("BrainCircuit")
export const Briefcase = make("Briefcase")
export const Building2 = make("Building2")
export const Calendar = make("Calendar")
export const CalendarClock = make("CalendarClock")
export const CalendarDays = make("CalendarDays")
export const Check = make("Check")
export const CheckCircle2 = make("CheckCircle2")
export const ChevronDown = make("ChevronDown")
export const ChevronLeft = make("ChevronLeft")
export const ChevronRight = make("ChevronRight")
export const CircleAlert = make("CircleAlert")
export const CircleArrowOutUpRight = make("CircleArrowOutUpRight")
export const CircleCheck = make("CircleCheck")
export const CircleDollarSign = make("CircleDollarSign")
export const CircleDot = make("CircleDot")
export const CircleX = make("CircleX")
export const ClipboardCheck = make("ClipboardCheck")
export const ClipboardList = make("ClipboardList")
export const Clock = make("Clock")
export const Clock3 = make("Clock3")
export const Cog = make("Cog")
export const Cpu = make("Cpu")
export const CreditCard = make("CreditCard")
export const Database = make("Database")
export const DoorOpen = make("DoorOpen")
export const Droplets = make("Droplets")
export const Eye = make("Eye")
export const EyeOff = make("EyeOff")
export const Factory = make("Factory")
export const FileBarChart = make("FileBarChart")
export const FileDown = make("FileDown")
export const FileUp = make("FileUp")
export const FileWarning = make("FileWarning")
export const FlaskConical = make("FlaskConical")
export const Fuel = make("Fuel")
export const Gauge = make("Gauge")
export const Globe = make("Globe")
export const Globe2 = make("Globe2")
export const HeartPulse = make("HeartPulse")
export const Hourglass = make("Hourglass")
export const Inbox = make("Inbox")
export const Info = make("Info")
export const Layers = make("Layers")
export const LayoutDashboard = make("LayoutDashboard")
export const ListChecks = make("ListChecks")
export const Loader2 = make("Loader2")
export const LogOut = make("LogOut")
export const Mail = make("Mail")
export const MapPin = make("MapPin")
export const Menu = make("Menu")
export const MessageSquare = make("MessageSquare")
export const Minus = make("Minus")
export const Moon = make("Moon")
export const MoreHorizontal = make("MoreHorizontal")
export const Package = make("Package")
export const PackageOpen = make("PackageOpen")
export const PackageSearch = make("PackageSearch")
export const PackageX = make("PackageX")
export const Pause = make("Pause")
export const Pencil = make("Pencil")
export const Phone = make("Phone")
export const Play = make("Play")
export const Plus = make("Plus")
export const Radar = make("Radar")
export const Radio = make("Radio")
export const Recycle = make("Recycle")
export const RefreshCw = make("RefreshCw")
export const RotateCcw = make("RotateCcw")
export const Search = make("Search")
export const SearchCheck = make("SearchCheck")
export const Send = make("Send")
export const Settings = make("Settings")
export const Settings2 = make("Settings2")
export const Shield = make("Shield")
export const ShieldAlert = make("ShieldAlert")
export const ShieldCheck = make("ShieldCheck")
export const Ship = make("Ship")
export const ShoppingBasket = make("ShoppingBasket")
export const ShoppingCart = make("ShoppingCart")
export const Snowflake = make("Snowflake")
export const Sparkles = make("Sparkles")
export const Sprout = make("Sprout")
export const SquareKanban = make("SquareKanban")
export const Store = make("Store")
export const Thermometer = make("Thermometer")
export const Timer = make("Timer")
export const Trash2 = make("Trash2")
export const TrendingDown = make("TrendingDown")
export const TrendingUp = make("TrendingUp")
export const TriangleAlert = make("TriangleAlert")
export const Truck = make("Truck")
export const Upload = make("Upload")
export const User = make("User")
export const UserPlus = make("UserPlus")
export const UserRound = make("UserRound")
export const UsersRound = make("UsersRound")
export const Wallet = make("Wallet")
export const Warehouse = make("Warehouse")
export const Waypoints = make("Waypoints")
export const Wheat = make("Wheat")
export const Wifi = make("Wifi")
export const Wrench = make("Wrench")
export const X = make("X")
export const XCircle = make("XCircle")
export const Zap = make("Zap")
