// Writes lib/icon-data.ts: the SVG of every icon in scripts/icon-map.mjs,
// taken from the Iconify sets installed as dev dependencies. The app
// ships only these few, with no request to Iconify at run time.
import { readFileSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { getIconData, iconToSVG } from "@iconify/utils"

import { ICONS } from "./icon-map.mjs"

const require = createRequire(import.meta.url)
const sets = {
  solar: require("@iconify-json/solar/icons.json"),
  tabler: require("@iconify-json/tabler/icons.json"),
}

const out = {}
for (const [name, id] of Object.entries(ICONS)) {
  const [prefix, icon] = id.split(":")
  const data = getIconData(sets[prefix], icon)
  if (!data) throw new Error(`Missing icon ${id} (for ${name})`)
  const svg = iconToSVG(data)
  let body = svg.body
  // Tabler draws at stroke 2; Solar at 1.5. Match Solar.
  if (prefix === "tabler") body = body.replaceAll('stroke-width="2"', 'stroke-width="1.5"')
  out[name] = { viewBox: svg.attributes.viewBox, body, id }
}

const header = `// Generated by scripts/build-icons.mjs from Iconify (Solar, Tabler).
// Do not edit by hand: change scripts/icon-map.mjs and run the script.
/* eslint-disable */
`
writeFileSync(
  new URL("../lib/icon-data.ts", import.meta.url),
  header + "export const ICON_DATA: Record<string, { viewBox: string; body: string; id: string }> = " + JSON.stringify(out, null, 1) + "\n"
)
console.log(`${Object.keys(out).length} icons written`)

// lib/icons.tsx: one component per name, drop-in for the lucide-react
// imports the app used to have (same names, same props).
const names = Object.keys(out)
const tsx = `// Generated by scripts/build-icons.mjs. Do not edit by hand.
"use client"

import { forwardRef, type CSSProperties, type ForwardRefExoticComponent, type RefAttributes, type SVGProps } from "react"

import { ICON_DATA } from "./icon-data"

export type IconProps = Omit<SVGProps<SVGSVGElement>, "ref"> & {
  /** Lucide's stroke width (2 = normal). Scaled to the icon set's 1.5. */
  strokeWidth?: number | string
  size?: number | string
}

export type LucideIcon = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>

function make(name: string): LucideIcon {
  const data = ICON_DATA[name]
  const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
    { strokeWidth, size = 24, style, className, ...rest },
    ref
  ) {
    const custom = strokeWidth !== undefined && Number(strokeWidth) !== 2
    const iconStyle: CSSProperties | undefined = custom
      ? { ...style, ["--icon-sw" as string]: String(Number(strokeWidth) * 0.75) }
      : style
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox={data.viewBox}
        fill="none"
        aria-hidden={rest["aria-label"] ? undefined : true}
        focusable="false"
        className={custom ? (className ? className + " icon-sw" : "icon-sw") : className}
        style={iconStyle}
        {...rest}
        dangerouslySetInnerHTML={{ __html: data.body }}
      />
    )
  })
  Icon.displayName = name
  return Icon
}

${names.map((n) => `export const ${n} = make(${JSON.stringify(n)})`).join("\n")}
`
writeFileSync(new URL("../lib/icons.tsx", import.meta.url), tsx)
console.log("lib/icons.tsx written")
